In [85]:
pwd

'C:\\Users\\91965'

In [86]:
import numpy as np
import pandas as pd
import seaborn as sb

In [87]:
data=pd.read_csv('c:/users/Ajetayrus/logistic_Regression_file.csv',header=0)

In [88]:
data.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

#Training a simple logistic model in pythonnn

In [89]:
X=data[["price"]]   #double brackets are given because independent vairable should be in two dimensional in sklearn

In [90]:
y=data["Sold"]

In [91]:
X.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [92]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [93]:
from sklearn.linear_model import LogisticRegression
#sklearn has 3 steps to complete the process
# first we create our classification object or model
#then we fit that object using our x and y vairables
#and the last step is to predict the y vairable using that trained classfication model

In [94]:
clf_lrs=LogisticRegression()

In [95]:
clf_lrs.fit(X,y)

LogisticRegression()

In [96]:
clf_lrs.coef_  #synatx to find the beta1 of the model

array([[-0.03571865]])

In [97]:
clf_lrs.intercept_ #syntax to find the beta0 of the model

array([0.61477516])

In [98]:
import statsmodels.api as sn

In [99]:
X_cons=sn.add_constant(X)

In [100]:
X_cons.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [101]:
import statsmodels.discrete.discrete_model as sm #syntax for importing the LR in the statsmodels

In [102]:
logit=sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [103]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Fri, 03 Nov 2023   Pseudo R-squ.:                 0.01788
Time:                        12:50:06   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

#  Logistic with multiple predictors

In [104]:
X=data.loc[:,data.columns!="Sold"] 
# we need all theindependent vairables except sold. so we add all the remaining vairables using : at first and later inside
# we mention that sold shoudnt be included as it is an dependent vairable


In [105]:
y=data['Sold']

In [106]:
clf_lr=LogisticRegression()

In [107]:
clf_lr.fit(X,y)

c:\users\91965\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [108]:
clf_lr.coef_

array([[-0.24635667, -0.01729747, -0.11019417,  0.86260547, -0.00599863,
         0.22819691, -0.21021774,  0.18006708, -0.0908669 , -0.00704722,
        -0.00499204, -0.32611296, -0.10521266, -0.09487364, -0.01512366,
         0.20180376]])

In [109]:
clf_lr.intercept_

array([0.0167128])

#using statsmodel 

In [110]:
X_cons=sn.add_constant(X)
logit=sm.Logit(y,X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [111]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Fri, 03 Nov 2023   Pseudo R-squ.:                  0.1924
Time:                        12:50:08   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

# predicting and confusion matrix

In [112]:
clf_lr.predict_proba(X)
#the first colmn in the output is the probablity of 0 that is not being sold
#the second column reprsents the probabiltiy if 1 that us being soldd

array([[0.12706708, 0.87293292],
       [0.39755021, 0.60244979],
       [0.98071884, 0.01928116],
       ...,
       [0.2859436 , 0.7140564 ],
       [0.28061211, 0.71938789],
       [0.16347233, 0.83652767]])

In [113]:
y_pred=clf_lr.predict(X)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [114]:
y_pred_03=clf_lr.predict_proba(X)[:,1]>=0.3
#now we are predicting the values of y using threshold as 0.3 

In [115]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [116]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)
#the values in the outputs gives the confusion matrix from where we can get the type1 error and type2 errors
#type1 error is like where the false statement is said in a true way(81 in the below output)
#type2 error is like where the true statement is said in a false way(80 in the below output)
#196 is where actual is no and pedicted as no
#149 is where actual is yes and predicted yess 

array([[196,  80],
       [ 81, 149]], dtype=int64)

In [117]:
#in the upper confusion matrix we took threshold as 0.5 and later we have created a predicted y with threshold 0.3 and now 
#we will get the confusion matrix
confusion_matrix(y,y_pred_03)

array([[121, 155],
       [ 18, 212]], dtype=int64)

# Evaluating model performance

# performance metrics 

 . precision= true positives/(true positives+false positives)
 . Recall = true positives/(true positives+false negatives)
 . AUC(ROC)

In [118]:
 #now we will import those from sklearn metrics
from sklearn.metrics import precision_score,recall_score

In [119]:
precision_score(y,y_pred)

0.6506550218340611

In [120]:
recall_score(y,y_pred)

0.6478260869565218

In [121]:
from sklearn.metrics import roc_auc_score

In [122]:
roc_auc_score(y,y_pred)

0.6789855072463769

# Linear Discriminant analysis

In [123]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [124]:
clf_lda=LinearDiscriminantAnalysis()
clf_lda.fit(X,y)

LinearDiscriminantAnalysis()

In [125]:
y_pred_lda=clf_lda.predict(X)

In [126]:
confusion_matrix(y,y_pred_lda)

array([[192,  84],
       [ 79, 151]], dtype=int64)

In [127]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [128]:
accuracy_score(y,y_pred_lda)

0.6778656126482213

# test train split

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [131]:
X_train.shape

(404, 16)

In [132]:
X_test.shape

(102, 16)

In [133]:
y_train.shape

(404,)

In [134]:
y_test.shape

(102,)

In [135]:
clf_LR=LogisticRegression()

In [136]:
clf_LR.fit(X_train,y_train)

c:\users\91965\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [137]:
y_test_pred=clf_LR.predict(X_test)

In [138]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [139]:
confusion_matrix(y_test,y_test_pred)

array([[37, 21],
       [14, 30]], dtype=int64)

In [140]:
accuracy_score(y_test,y_test_pred)

0.6568627450980392

# LDA for train test dataa

In [141]:
clf_LDA=LinearDiscriminantAnalysis()

In [142]:
clf_LDA.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [143]:
y_test_pred=clf_LDA.predict(X_test)

In [144]:
confusion_matrix(y_test,y_test_pred)

array([[34, 24],
       [11, 33]], dtype=int64)

In [145]:
accuracy_score(y_test,y_test_pred)

0.6568627450980392

# K Nearest Neighbors

In [146]:
from sklearn import preprocessing

In [149]:
#before running a knn model we need standardize our training data and test data
scaler=preprocessing.StandardScaler().fit(X_train)
X_train_s=scaler.transform(X_train)

In [150]:
scaler=preprocessing.StandardScaler().fit(X_test)
X_test_s=scaler.transform(X_test)

In [156]:
from sklearn.neighbors import KNeighborsClassifier 
#here we will take k=1 
clf_knn_1=KNeighborsClassifier(n_neighbors=1)

In [159]:
clf_knn_1.fit(X_train_s,y_train)

KNeighborsClassifier(n_neighbors=1)

In [160]:
y_test_s_pred=clf_knn_1.predict(X_test_s)

In [161]:
confusion_matrix(y_test,y_test_s_pred)

array([[30, 28],
       [19, 25]], dtype=int64)

In [162]:
accuracy_score(y_test,y_test_s_pred)

0.5392156862745098

In [163]:
#now we will take k=3
clf_knn_3=KNeighborsClassifier(n_neighbors=3)
clf_knn_3.fit(X_train_s,y_train)

KNeighborsClassifier(n_neighbors=3)

In [166]:
y_test_s_pred3=clf_knn_3.predict(X_test_s)

In [167]:
confusion_matrix(y_test,y_test_s_pred3)

array([[32, 26],
       [21, 23]], dtype=int64)

In [168]:
accuracy_score(y_test,y_test_s_pred3)

0.5392156862745098

In [ ]:
#just now we did the classification for k=1 and k=3 and got some results
#now we will see how we can work with multiple k values at the same time

In [170]:
from sklearn.model_selection import GridSearchCV

In [172]:
#now we will create a dictionary to store the k values
params={'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [173]:
#now we create an object and we give two arguments. one is knn and other is the dict we created with 10 values
grid_search_cv=GridSearchCV(KNeighborsClassifier(),params)

In [174]:
#now we fit our model with data
grid_search_cv.fit(X_train_s,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [176]:
grid_search_cv.best_params_ #this syntax will give the best parameter out of 10

{'n_neighbors': 9}

In [177]:
optimized_KNN=grid_search_cv.best_estimator_ #this particular  syntax will take the best one out of 10

In [179]:
y_test_pred_oknn=optimized_KNN.predict(X_test_s)

In [180]:
confusion_matrix(y_test,y_test_pred_oknn)

array([[36, 22],
       [18, 26]], dtype=int64)

In [181]:
accuracy_score(y_test,y_test_pred_oknn)

0.6078431372549019