Numpy

In [2]:
import numpy as np

In [4]:
np1 = np.array([1,2,3,4])

In [6]:
np1

array([1, 2, 3, 4])

In [8]:
type(np1)

numpy.ndarray

In [11]:
Mat1 = np.array([[1,2],[3,4]])

In [13]:
Mat1

array([[1, 2],
       [3, 4]])

In [15]:
np1.shape

(4,)

In [17]:
Mat1.shape

(2, 2)

In [19]:
Mat1.dtype

dtype('int32')

In [21]:
Mat1[0,0] = 10

In [23]:
Mat1

array([[10,  2],
       [ 3,  4]])

In [26]:
Mat2=np.arange(0,20,2)

In [28]:
Mat2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
Mat3=np.linspace(0,10,20)

In [31]:
Mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
Mat3.shape

(20,)

In [35]:
Mat4=np.random.rand(10,10)

In [38]:
Mat4

array([[0.2042413 , 0.76409403, 0.47513795, 0.05992314, 0.96684452,
        0.7569511 , 0.23759049, 0.57181192, 0.64465088, 0.98063782],
       [0.77793765, 0.56052224, 0.51020881, 0.18616928, 0.65236123,
        0.27658   , 0.76972946, 0.54463933, 0.75229721, 0.79920608],
       [0.94435777, 0.85439731, 0.29728303, 0.6123625 , 0.218116  ,
        0.04394406, 0.60143659, 0.15257471, 0.16811854, 0.02298779],
       [0.70712964, 0.38781831, 0.28903918, 0.95922879, 0.09944606,
        0.26055622, 0.11036949, 0.52867977, 0.11353243, 0.73972816],
       [0.39884469, 0.06945704, 0.12759173, 0.06404501, 0.25153642,
        0.89848165, 0.93492123, 0.45093903, 0.23117396, 0.04148317],
       [0.00419502, 0.24688202, 0.26084885, 0.25496472, 0.24772823,
        0.6910082 , 0.26856387, 0.40239668, 0.03908551, 0.69482914],
       [0.93814798, 0.52499361, 0.94881629, 0.83177106, 0.80866781,
        0.29970109, 0.35055606, 0.34616823, 0.98890019, 0.85109489],
       [0.80089057, 0.3395694 , 0.5897355

In [40]:
Mat5=np.random.randn(2,3)

In [42]:
Mat5

array([[-1.42427521,  1.83992008,  0.28538396],
       [-0.68046124,  0.07337175,  0.66932196]])

In [44]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
np.ones((4,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.full((4,5),23)

array([[23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23],
       [23, 23, 23, 23, 23]])

In [54]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
x=np.array([1,2,3])
y=np.array([3,4,5])
z=[23,23,23]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  4,  5, 23, 23, 23])

In [60]:
surya=np.array([[12,12,12],[23,23,23]])
np.concatenate([surya,surya])

array([[12, 12, 12],
       [23, 23, 23],
       [12, 12, 12],
       [23, 23, 23]])

In [67]:
x=np.array([1,2,3])
surya=np.array([[4,5,6],[7,8,9]])
np.vstack([x,surya])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
x=np.array([[9],[9]])
np.hstack([surya,x])

array([[4, 5, 6, 9],
       [7, 8, 9, 9]])

In [71]:
import numpy as surya

In [73]:
surya1=np.array([5,5])

In [75]:
surya1

array([5, 5])

In [76]:
type(surya1)

numpy.ndarray